### ISSUE TITLE
Syntax error, unexpected '|', expecting ';' or '{'

### ISSUE THREAD

**Issue by vicegold** [cp6/BunnyCDN-API#11]
Always getting this error, no matter if I try on PHP 7.4 or 8.0

```Parse error: syntax error, unexpected '|', expecting ';' or '{' in /vendor/corbpie/bunny-cdn-api/src/BunnyAPI.php on line 294```

Any ideas?

**Comment by cp6** [comment]
Based on that line number it is `convertBytes()` function with its union type returns.

[Union types only work from version 8.0.0 onwards](https://php.watch/versions/8.0/union-types), are you sure you had PHP version 8.0.0 enabled?

I just tested then

`echo phpversion();` was 8.0.2

`echo $bunny->convertBytes(4500000, 'MB');` was 4.29 and no errors.

**Comment by vicegold** [comment]
That must have been my issue. Tried again on a different computer and it works fine there with PHP8.0. Sorry!
