### ISSUE TITLE
purgeCache returns always a 400

### ISSUE THREAD

**Issue by gb5256** [cp6/BunnyCDN-API#25]
Not sure if this is my fault...

If I use the example:

    $bunny->purgeCache('https://cdn.domain.com/css/style.min.css')

It returns a 400 code.
Of course I do not have access to cdn.domain.com, but if I try this here:
https://docs.bunny.net/reference/purgepublic_indexpost
Then I get a 404 repsonse with this additional info:

      {
      "ErrorKey": "pullZone.not_found",
      "Field": "PullZone",
      "Message": "The requested Pull Zone was not found"
    }

So my question is why does this return a 400 when using this exension?
Also: this is the respone I get back:

     {"ErrorKey":"purge.urls_invalid","Field":"Urls","Message":"The purge request must contain at least one and no more than 50 URLs"}

And besides this, even If I try to use a pull zone where I have access to, it also always returns a 400 and does not purge.

Any idea?
Can somebody confirm that this exenstion is indeed purging correctly right now and also does return a 200 code on success?

Thanks,
gb5256

**Comment by cp6** [comment]
Hello

Thank you for bringing this to my attention and providing the info. I checked it out and cross-referenced the docs and it does appear that it was not functioning correctly. I have now fixed it up: https://github.com/cp6/BunnyCDN-API/commit/14405fa4a5cc656298055793cfcd2b692ceea06a

Please do let me know if you are still having an issue with it.
