### ISSUE TITLE
Is there a smart fileExists method?

### ISSUE THREAD

**Issue by gb5256** [cp6/BunnyCDN-API#30]
Hi,

sometimes I need to check if a file exists on the storage.
I currently just get the folder via listFiles and then check if the return array does contain the file.
But this can take quite some time as I might have thousands of files in the folder.
Is there a more clever way to do this?

Thanks for any ideas on this.
gb5256

**Comment by cp6** [comment]
Hi
Is this when you already know the directory and file and need to confirm it exists?

**Comment by cp6** [comment]
It's now been added https://github.com/cp6/BunnyCDN-API/commit/15eed34d7688c0da462e1a0d31a0d16de9dc16d5

`$bunny->fileExists($file);`

`$bunny->fileExists('folder/anotherfolder/file.jpg');`
