### ISSUE TITLE
Does 1.9.5 contains the new fileExists() ?

### ISSUE THREAD

**Issue by gb5256** [cp6/BunnyCDN-API#32]
Just did an composer update and it says in my composer.lock that corbpie/bunny-cdn-api is now at v1.9.5 but looking at the code it downloaded, it does not contain the new fileExists() function.
Or am I doing something wrong?

Do I need to use your dev branch?
I am using master like this: "corbpie/bunny-cdn-api" : "*",

I have also deleted the corbpie folder from vendor and did again a composer update, still the same.

Thanks for any ideas.
gb5256

**Comment by cp6** [comment]
Sorry for the late response with this one, yes it was in the Dev branch but is now in the main release.
