### ISSUE TITLE
folderExists not working?

### ISSUE THREAD

**Issue by gb5256** [cp6/BunnyCDN-API#33]
I am trying this:

              if ( $CDNStorage->folderExists($target) === false ) {  
                              $CDNStorage->createFolder($target);
              }

This throws error like "can not create folder as it already exists".
So the folderExist does return false even that the folder exists already.

Any ideas?
gb5256

**Comment by cp6** [comment]
Thanks for this. Fixed it [here](https://github.com/cp6/BunnyCDN-API/commit/655207e3020852233147435568a505fd0da31b07). These warning messages can only be suppressed with @ which isn't ideal but with proper conditionals, it should be ok.
