### ISSUE TITLE
dirSize seems to need leading slash for dir while other functions dont

### ISSUE THREAD

**Issue by gb5256** [cp6/BunnyCDN-API#35]
Check this:

Your DirSize function needs a leading slash for the DIR or will just get zero size back (like the folder does not exist at all).
$bunny->dirSize("/pets");

While other functions do not need to have a leading slash.
$bunny->folderExists("pets");

gb5256

**Comment by cp6** [comment]
Thanks for picking this up, will fix it.

**Comment by cp6** [comment]
fixed here https://github.com/cp6/BunnyCDN-API/commit/45f103ab3e4f7e83c143c4f0879d07740858cf1e
