### ISSUE TITLE
Composer support?

### ISSUE THREAD

**Issue by macbookandrew** [cp6/BunnyCDN-API#4]
Any thoughts about adding composer support for easier use and updates in other projects? I’d be happy to assist if you want.

**Comment by cp6** [comment]
I think that is a great idea, I will need your help with it.

I made a start (hopefully correctly):

[commit/fc4b6abfe03aeec4418a9c4ae4879ace68dd732f](https://github.com/cp6/BunnyCDN-API/commit/fc4b6abfe03aeec4418a9c4ae4879ace68dd732f)

**Comment by cp6** [comment]
@macbookandrew what is the usage after using composer?

```
<?php
require __DIR__ . '/vendor/autoload.php';
use Corbpie\BunnyCdn;
$bunny = new BunnyAPI();
```
?

Gives: Fatal error: Uncaught Error: Class 'BunnyAPI' not found

Not sure if it is my setup
