### ISSUE TITLE
Which PHP version to use?

### ISSUE THREAD

**Issue by Zebraslive** [cp6/BunnyCDN-API#8]
I got an error about php version.
"Package corbpie/bunny-cdn-api at version  has a PHP requirement incompatible with your PHP version (7.3.11)"

Which php versions are supported?

**Comment by Zebraslive** [comment]
@cp6 @macbookandrew @Xarex

**Comment by cp6** [comment]
Min version 7.4

As per `composer.json` 

```
  "require": {
    "php": ">=7.4",
    "ext-ftp": "*"
  },
```

**Comment by Zebraslive** [comment]
Thanks! Can't believe I didn't think to check that.
